spring:
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/views/
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://127.0.0.1:3306/yanweitong?useUnicode=true&characterEncoding=UTF-8
    dbcp2:
      initial-size: 20
      max-total: 100
      min-idle: 10
      time-between-eviction-runs-millis: 360000
      test-on-borrow: true
      test-on-return: false
      test-while-idle: true
      validation-query: SELECT 1
  jpa:
      show-sql: false
      hibernate:
        ddl-auto: update
      database: mysql
      open-in-view: true
      properties:
        hibernate:
          enable_lazy_load_no_trans: true
  http:
      multipart:
        max-file-size: 100MB